#!/bin/bash

echo "[+] Ensure IPV6 loopback is configured"

# Check if IPv6 is disabled
ipv6_disabled=$(grep "^\s*linux" /boot/grub/grub.cfg | grep -v ipv6.disable=1)

if [[ -n "$ipv6_disabled" ]]; then
  echo ""
else
  # Verify ip6tables rules
  input_rules=$(ip6tables -L INPUT -v -n)
  output_rules=$(ip6tables -L OUTPUT -v -n)

  # Verify loopback rules for INPUT chain
  expected_input_rules="-i lo -j ACCEPT"
  if ! echo "$input_rules" | grep -q "$expected_input_rules"; then
    echo ""
    ip6tables -A INPUT -i lo -j ACCEPT
    ip6tables -A INPUT -s ::1 -j DROP
  else
    echo ""
  fi

  # Verify loopback rules for OUTPUT chain
  expected_output_rules="-o lo -j ACCEPT"
  if ! echo "$output_rules" | grep -q "$expected_output_rules"; then
    echo ""
    ip6tables -A OUTPUT -o lo -j ACCEPT
  else
    echo ""
  fi
fi

